# Generated by Django 5.2.6 on 2025-09-22 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('IT_ADMIN', 'IT Administration'), ('PROCUREMENT', 'Procurement'), ('FINANCE', 'Finance'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business Studies'), ('MEDICINE', 'Medicine'), ('EDUCATION', 'Education')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='core_custom_role_77f64b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='core_custom_departm_cd171c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='core_custom_usernam_8458f1_idx'),
        ),
    ]
