# Generated by Django 5.2.6 on 2025-09-22 01:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRequest',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('department', models.CharField(choices=[('IT_ADMIN', 'IT Administration'), ('PROCUREMENT', 'Procurement'), ('FINANCE', 'Finance'), ('COMPUTER_SCIENCE', 'Computer Science'), ('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business Studies'), ('MEDICINE', 'Medicine'), ('EDUCATION', 'Education')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='core.departmentrequest')),
            ],
            options={
                'verbose_name_plural': 'Approval Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['status'], name='core_depart_status_0628f9_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['priority'], name='core_depart_priorit_b297b6_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['department'], name='core_depart_departm_181ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentrequest',
            index=models.Index(fields=['created_at'], name='core_depart_created_2c759d_idx'),
        ),
    ]
