# Generated by Django 5.2.6 on 2025-09-22 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departmentrequest_approvalhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Approval Flow', max_length=100)),
                ('stages', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('STORES_MANAGER', 'Stores Manager Approval'), ('PROCUREMENT_OFFICER', 'Procurement Officer Approval'), ('CFO', 'Chief Financial Officer Approval'), ('COMPLETED', 'Approval Completed')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_approvals', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='core.departmentrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['stage'], name='core_approv_stage_170e7b_idx'), models.Index(fields=['completed'], name='core_approv_complet_1edff5_idx'), models.Index(fields=['due_date'], name='core_approv_due_dat_929d54_idx')],
            },
        ),
    ]
