# Generated by Django 5.2.6 on 2025-09-22 01:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_approvalflow_approvalstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('original_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('current_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_each', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='core.category')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item_name'], name='core_stock_item_na_170c00_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['location'], name='core_stock_locatio_0fe261_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['category'], name='core_stock_categor_561eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['available'], name='core_stock_availab_f30faf_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['current_quantity'], name='core_stock_current_e3dd16_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='core_stockm_movemen_60f0ad_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='core_stockm_created_a48320_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference'], name='core_stockm_referen_04fea4_idx'),
        ),
    ]
