# Generated by Django 5.2.6 on 2025-09-22 01:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_stock_stockmovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('severity', models.CharField(choices=[('MINOR', 'Minor Damage'), ('MODERATE', 'Moderate Damage'), ('SEVERE', 'Severe Damage'), ('TOTAL', 'Total Loss')], default='MODERATE', max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_damages', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_damages', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='core.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_number'], name='core_damage_report__719fe5_idx'), models.Index(fields=['severity'], name='core_damage_severit_2afb9c_idx'), models.Index(fields=['resolved'], name='core_damage_resolve_3669de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=20, unique=True)),
                ('supplier', models.CharField(max_length=200)),
                ('ordered_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('PARTIAL', 'Partially Received'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.stock')),
            ],
            options={
                'ordering': ['-expected_date'],
                'indexes': [models.Index(fields=['delivery_number'], name='core_delive_deliver_fcf2c6_idx'), models.Index(fields=['status'], name='core_delive_status_d4973b_idx'), models.Index(fields=['expected_date'], name='core_delive_expecte_8ebaf0_idx'), models.Index(fields=['supplier'], name='core_delive_supplie_bdecaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relocation_number', models.CharField(max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relocations', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='core.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['relocation_number'], name='core_reloca_relocat_29891e_idx'), models.Index(fields=['from_location'], name='core_reloca_from_lo_74257f_idx'), models.Index(fields=['to_location'], name='core_reloca_to_loca_0586c3_idx'), models.Index(fields=['completed'], name='core_reloca_complet_ce4665_idx')],
            },
        ),
    ]
